# identify the bussiness problem

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv("banana_quality_dataset.csv")

In [3]:
#basic checks
df.head()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,1,Manzano,Colombia,1.88,Processing,2.11,Turning,16.83,3.53,21.44,146.92,2023-10-16,13.7,58.2,2440.5,183.6
1,2,Plantain,Guatemala,2.42,Processing,4.25,Ripe,16.73,4.09,26.11,160.48,2023-10-14,5.1,280.2,2374.6,109.8
2,3,Burro,Ecuador,3.57,Premium,6.24,Overripe,21.34,1.63,25.20,225.27,2023-09-08,17.7,1246.9,1191.5,147.7
3,4,Manzano,Ecuador,2.21,Processing,5.39,Ripe,16.75,3.31,13.08,137.80,2023-10-07,13.0,1150.2,2845.1,92.8
4,5,Red Dacca,Ecuador,2.35,Processing,5.84,Ripe,16.90,3.07,12.98,227.84,2023-10-02,4.8,526.0,2136.9,129.7

In [4]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sample_id           1000 non-null   int64
 1   variety             1000 non-null   object
 2   region              1000 non-null   object
 3   quality_score       1000 non-null   float64
 4   quality_category    1000 non-null   object
 5   ripeness_index      1000 non-null   float64
 6   ripeness_category   1000 non-null   object
 7   sugar_content_brix  1000 non-null   float64
 8   firmness_kgf        1000 non-null   float64
 9   length_cm           1000 non-null   float64
 10  weight_g            1000 non-null   float64
 11  harvest_date        1000 non-null   object
 12  tree_age_years      1000 non-null   float64
 13  altitude_m          1000 non-null   float64
 14  rainfall_mm         1000 non-null   float64
 15  soil_nitrogen_ppm   1000 non-null   float64
dtypes: float64(10), int64(1), object(5)
memory usage: 125.1+ KB

In [5]:
df.shape

(1000, 16)

In [6]:
df.describe()

,sample_id,quality_score,ripeness_index,sugar_content_brix,firmness_kgf,length_cm,weight_g,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,2.465160,4.042170,18.516830,2.706840,19.882100,164.738930,10.879600,723.556700,1972.992800,104.391300
std,288.819436,0.540909,1.753211,2.034812,1.289252,5.736318,49.163073,5.215554,427.372855,564.467912,53.607794
min,1.000000,0.920000,1.020000,15.000000,0.500000,10.000000,81.050000,2.000000,0.400000,1000.500000,10.000000
25%,250.750000,2.090000,2.447500,16.827500,1.590000,14.902500,122.397500,6.300000,353.950000,1498.750000,60.150000
50%,500.500000,2.440000,4.110000,18.500000,2.680000,19.890000,163.365000,10.700000,726.000000,1957.400000,104.100000
75%,750.250000,2.850000,5.562500,20.312500,3.820000,24.800000,205.775000,15.600000,1071.725000,2431.800000,149.850000
max,1000.000000,3.890000,7.000000,21.980000,5.000000,29.950000,249.890000,20.000000,1498.400000,2992.000000,199.900000

In [7]:
#drop 
df.drop(["sample_id","harvest_date"],axis=1,inplace=True)

In [8]:
df.shape

(1000, 14)

In [9]:
#EDA 
#preprocessing

In [10]:
 #target variable quality category
y=df['quality_category']

In [11]:
x =df.drop(['quality_category'],axis=1)

In [12]:
x.shape

(1000, 13)

In [18]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,StandardScaler
le=LabelEncoder()
y=le.fit_transform(y)
print(le.classes_)

[0 1 2 3]

In [14]:
x.drop(["firmness_kgf","variety","weight_g","altitude_m","soil_nitrogen_ppm"],axis=1,inplace=True)

In [19]:
#apply columntransformer 
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,3,]),
                                   ("sc",StandardScaler(),[1,2,4,5,6,7])])

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [21]:
x_train_transform=ct.fit_transform(x_train)
x_train_transform=pd.DataFrame(x_train_transform)

In [22]:
x_train_transform.shape

(800, 8)

In [23]:
x_test_transform=ct.fit_transform(x_test)
x_test_transform=pd.DataFrame(x_test_transform)

# import libraries

In [24]:
from tensorflow.keras.models import Sequential

In [28]:
from keras.layers import Dense,BatchNormalization

# iniatlize

In [29]:
model=Sequential()

## add layers

In [30]:
# input layer + hidden layes
model.add(Dense(units=64,activation="relu",input_shape=(x_train_transform.shape[1],)))
model.add(BatchNormalization())
## hiden layer 2
model.add(Dense(units=10,activation="relu"))
model.add(BatchNormalization())
## output layer
model.add(Dense(units=4,activation="softmax"))

C:\Users\admin\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 64)                  │             576 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 64)                  │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             650 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 10)                  │              40 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,566 (6.12 KB)

 Trainable params: 1,418 (5.54 KB)

 Non-trainable params: 148 (592.00 B)

# compile model

In [32]:
model.compile(optimizer="sgd",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

 # Train Model

In [33]:
hist=model.fit(x_train_transform,y_train,epochs=50,verbose=1,validation_split=0.2,batch_size=32)

Epoch 1/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.2719 - loss: 1.6233 - val_accuracy: 0.5125 - val_loss: 1.3042
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5281 - loss: 1.0958 - val_accuracy: 0.6000 - val_loss: 1.1398
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6781 - loss: 0.9292 - val_accuracy: 0.7250 - val_loss: 1.0171
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7422 - loss: 0.8115 - val_accuracy: 0.8062 - val_loss: 0.9269
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7812 - loss: 0.7480 - val_accuracy: 0.8625 - val_loss: 0.8494
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8250 - loss: 0.6622 - val_accuracy: 0.9000 - val_loss: 0.7731
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8453 - loss: 0.6008 - val_accuracy: 0.9125 - val_loss: 0.6971
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8406 - loss: 0.5628 - val_accuracy: 0.9125 - val_loss: 0.6394
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8672 - loss: 0.5052 - val_accuracy: 0.9125 - val_loss: 0.5837
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8875 - loss: 0.4805 - val_accuracy: 0.9250 - val_loss: 0.5305
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8781 - loss: 0.4629 - val_accuracy: 0.9250 - val_loss: 0.4940
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8781 - loss: 0.4416 - val_accuracy: 0.9312 - val_loss: 0.4495
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8984 - loss: 0.4091 - val_accuracy: 0.9375 - val_loss: 0.4200
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8984 - loss: 0.3907 - val_accuracy: 0.9438 - val_loss: 0.3839
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8906 - loss: 0.3808 - val_accuracy: 0.9438 - val_loss: 0.3493
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8938 - loss: 0.3596 - val_accuracy: 0.9500 - val_loss: 0.3174
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9109 - loss: 0.3326 - val_accuracy: 0.9438 - val_loss: 0.2962
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8969 - loss: 0.3391 - val_accuracy: 0.9563 - val_loss: 0.2776
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9047 - loss: 0.3140 - val_accuracy: 0.9500 - val_loss: 0.2583
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9125 - loss: 0.2984 - val_accuracy: 0.9500 - val_loss: 0.2387
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9219 - loss: 0.2941 - val_accuracy: 0.9563 - val_loss: 0.2220
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9078 - loss: 0.2874 - val_accuracy: 0.9625 - val_loss: 0.2129
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9203 - loss: 0.2647 - val_accuracy: 0.9625 - val_loss: 0.1980
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9172 - loss: 0.2608 - val_accuracy: 0.9750 - val_loss: 0.1922
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9094 - loss: 0.2642 - val_accuracy: 0.9625 - val_loss: 0.1773
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9203 - loss: 0.2650 - val_accuracy: 0.9625 - val_loss: 0.1740
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9219 - loss: 0.2568 - val_accuracy: 0.9688 - val_loss: 0.1627
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9156 - loss: 0.2382 - val_accuracy: 0.9688 - val_loss: 0.1552
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9234 - loss: 0.2190 - val_accuracy: 0.9625 - val_loss: 0.1524
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9281 - loss: 0.2285 - val_accuracy: 0.9500 - val_loss: 0.1515
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9312 - loss: 0.2157 - val_accuracy: 0.9750 - val_loss: 0.1353
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9172 - loss: 0.2195 - val_accuracy: 0.9563 - val_loss: 0.1322
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9078 - loss: 0.2416 - val_accuracy: 0.9688 - val_loss: 0.1270
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8969 - loss: 0.2641 - val_accuracy: 0.9625 - val_loss: 0.1350
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9266 - loss: 0.2165 - val_accuracy: 0.9563 - val_loss: 0.1359
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9391 - loss: 0.1860 - val_accuracy: 0.9563 - val_loss: 0.1232
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9297 - loss: 0.1930 - val_accuracy: 0.9750 - val_loss: 0.1103
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9281 - loss: 0.1998 - val_accuracy: 0.9625 - val_loss: 0.1199
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9172 - loss: 0.2226 - val_accuracy: 0.9688 - val_loss: 0.1152
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9359 - loss: 0.1851 - val_accuracy: 0.9812 - val_loss: 0.1037
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9266 - loss: 0.1926 - val_accuracy: 0.9688 - val_loss: 0.1099
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9344 - loss: 0.1896 - val_accuracy: 0.9500 - val_loss: 0.1238
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9484 - loss: 0.1579 - val_accuracy: 0.9625 - val_loss: 0.1006
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9359 - loss: 0.1830 - val_accuracy: 0.9500 - val_loss: 0.1244
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9203 - loss: 0.2059 - val_accuracy: 0.9750 - val_loss: 0.0993
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9484 - loss: 0.1765 - val_accuracy: 0.9688 - val_loss: 0.0986
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9484 - loss: 0.1438 - val_accuracy: 0.9812 - val_loss: 0.0964
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9359 - loss: 0.1848 - val_accuracy: 0.9688 - val_loss: 0.0966
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9328 - loss: 0.1825 - val_accuracy: 0.9812 - val_loss: 0.0969
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9406 - loss: 0.1714 - val_accuracy: 0.9875 - val_loss: 0.0897

# evalute

In [34]:
acc=model.evaluate(x_test_transform,y_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9300 - loss: 0.2309

In [36]:
import matplotlib.pyplot as plt

#Extract metrics from the history object
acc = hist.history['r2_score']
val_acc = hist.history['val_r2_score']
loss = hist.history['loss']
val_loss = hist.history['val_loss']
epochs = range(1, len(acc) + 1)

#Plot Accuracy
plt.figure(figsize=(10, 4))
plt.title("Results with adam")
plt.subplot(1, 2, 1)
plt.plot(epochs, acc, 'bo-', label='Training Accuracy')
plt.plot(epochs, val_acc, 'ro-', label='Validation Accuracy')
plt.title('Model Accuracy Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

#Plot Loss
plt.subplot(1, 2, 2)
plt.plot(epochs, loss, 'bo-', label='Training Loss')
plt.plot(epochs, val_loss, 'ro-', label='Validation Loss')
plt.title('Model Loss Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

KeyError: 'r2_score'